Erreur inconnue (veuillez faire un rapport de bug) : <type 'exceptions.AttributeError'>\n
Sa valeur est : AttributeError("'dict' object has no attribute 'x'",)
  File "<script>", line 40, in <module>
  File "<script>", line 19, in init
  File "<script>", line 4, in getLandingZone
