Erreur inconnue (veuillez faire un rapport de bug) : <type 'exceptions.AttributeError'>\n
Sa valeur est : AttributeError("'dict' object has no attribute 'y'",)
  File "<script>", line 37, in <module>
  File "<script>", line 16, in init
  File "<script>", line 4, in getLandingZone
