Erreur de nom : vous semblez utiliser un identifiant qui n'existe pas. Auriez-vous fait une typo ?
NameError("global name 'self' is not defined",)
  File "<script>", line 8, in <module>
  File "<script>", line 10, in RecListToArray
