L'exécution de votre programme a déclenché une exception java.lang.ArrayIndexOutOfBoundsException : 4
 Merci de corriger votre code.
   at plm.runtime15.LangtonsAnt$$anonfun$step$1.apply$mcVI$sp (plm.runtime15.LangtonsAnt:21)
   at scala.collection.immutable.Range.foreach$mVc$sp (Range.scala:141)
   at plm.runtime15.LangtonsAnt.step (plm.runtime15.LangtonsAnt:19)
   at plm.runtime15.LangtonsAnt$$anonfun$run$2.apply$mcVI$sp (plm.runtime15.LangtonsAnt:63)
   at scala.collection.immutable.Range.foreach$mVc$sp (Range.scala:141)
   at plm.runtime15.LangtonsAnt.run (plm.runtime15.LangtonsAnt:61)
   at plm.core.lang.JVMCompiledLang.runEntity (null:-1)
   at plm.universe.World$1.run (null:-1)
   at java.lang.Thread.run (null:-1)
