Le monde 'array123' diffère:
array123(Array(1,1,2,4,1)) returned Ce test a levé une exception scala.MatchError : 4 (of class java.lang.Integer) while false were expected.

