Erreur de nom : vous semblez utiliser un identifiant qui n'existe pas. Auriez-vous fait une typo ?
NameError("global name 'seenError' is not defined",)
  File "<script>", line 2, in <module>
  File "<script>", line -18, in forward
