Erreur de type : vous n'utilisez pas correctement une fonction, ou quelque chose du genre.
TypeError("'plm.universe.Direction' object is not callable",)
  File "<script>", line 15, in <module>
  File "<script>", line 2, in move
