Erreur inconnue (veuillez faire un rapport de bug) : <type 'exceptions.AttributeError'>\n
Sa valeur est : AttributeError("type object 'plm.universe.Direction' has no attribute 'North'",)
  File "<script>", line 2, in <module>
