Erreur inconnue (veuillez faire un rapport de bug) : <type 'exceptions.AttributeError'>\n
Sa valeur est : AttributeError("type object 'plm.universe.Direction' has no attribute 'West'",)
  File "<script>", line 6, in <module>
